
    /* eslint-disable */
    /* tslint:disable */
    
    // generated by react-imported-component, DO NOT EDIT     
    import {assignImportedComponents} from 'react-imported-component/macro';
    undefined    
    
    // all your imports are defined here
    // all, even the ones you tried to hide in comments (that's the cost of making a very fast parser)
    // to remove any import from here
    // 1) use magic comment `import(/* client-side */ './myFile')` - and it will disappear
    // 2) use file filter to ignore specific locations (refer to the README - https://github.com/theKashey/react-imported-component/#server-side-auto-import)
    // 3) use .imported.js to control this table generation (refer to the README - https://github.com/theKashey/react-imported-component/#-imported-js)
    
    const applicationImports = assignImportedComponents([
      [() => import('./client/bootstrap'), '', './src/client/bootstrap', false] /* from ./src/client/index.tsx */,
      [() => import('./client/services/msw/browser'), '', './src/client/services/msw/browser', false] /* from ./src/client/index.tsx */,
      [() => import('app1/Card'), '', 'app1/Card', false] /* from ./src/client/pages/HomePage.tsx */,
      [() => import('app1/Counter'), '', 'app1/Counter', false] /* from ./src/client/pages/HomePage.tsx */,
      [() => import('app1/Header'), '', 'app1/Header', false] /* from ./src/client/pages/HomePage.tsx */,
      [() => import('app2/App2'), '', 'app2/App2', false] /* from ./src/client/pages/HomePage.tsx */,
      [() => import('app4/Title'), '', 'app4/Title', false] /* from ./src/client/pages/HomePage.tsx */,
    ]);
    
    export default applicationImports;
    
    // @ts-ignore
    if (module.hot) {
       // these imports would make this module a parent for the imported modules.
       // but this is just a helper - so ignore(and accept!) all updates
       
       // @ts-ignore
       module.hot.accept(() => null);
    }    
    